all:04

04: 08_04.o History.o Bio.o Book.o 
	g++ -o 04 08_04.o History.o Bio.o Book.o
	
08_04.o: 08_04.cpp
	g++ -c 08_04.cpp
	
History.o: History.cpp
	g++ -c History.cpp

Bio.o: Bio.cpp
	g++ -c Bio.cpp

Book.o: Book.cpp
	g++ -c Book.cpp

