all:09

09: 11_09.o Stack.o ExcRange.o
	g++ -o 09 11_09.o Stack.o ExcRange.o
	
11_09.o: 11_09.cpp
	g++ -c 11_09.cpp
	
Stack.o: Stack.cpp
	g++ -c Stack.cpp

ExcRange.o: ExcRange.cpp
	g++ -c ExcRange.cpp
