all:05

05: 08_05.o Employee.o Publication.o Professor.o
	g++ -o 05 08_05.o Employee.o Publication.o Professor.o
	
08_05.o: 08_05.cpp
	g++ -c 08_05.cpp
	
Employee.o: Employee.cpp
	g++ -c Employee.cpp
	
Publication.o: Publication.cpp
	g++ -c Publication.cpp
	
Professor.o: Professor.cpp
	g++ -c Professor.cpp
