all:08

08: 11_08.o Stack.o ExcRange.o
	g++ -o 08 11_08.o Stack.o ExcRange.o
	
11_08.o: 11_08.cpp
	g++ -c 11_08.cpp
	
Stack.o: Stack.cpp
	g++ -c Stack.cpp

ExcRange.o: ExcRange.cpp
	g++ -c ExcRange.cpp
